### PR TITLE
feat: Update to electron 15.5.7 by using @electron/remote

### PR DESCRIPTION
**Pull request by ztalbot2000**
Electron V15 deprecated electron/remote in favour of IPC messaging which fixing is beyond my immediate needs, however there is @@electron/remote which puts back this capability.
After pre-build, build and test all seems to be working.

I did not bump the version as I was not sure what you would bump it to

### CODE REVIEW

**Comment by ztalbot2000** [comment]
For those who need this before or if its ever merged, it can be added to your project by adding the following to your package.json
"floss": "git://github.com/ztalbot2000/floss#f2de91cc36f25809ee4cb6458da30a4facad91b6",

Enjoy

**Comment by bigtimebuddy** [comment]
Thanks for this @ztalbot2000. Do you know if this still works with v12? Are these changes backward compatible or do we need to adjust the lower version too?

**Comment by ztalbot2000** [comment]
Hi,

   I really don't know if they are backward compatible. I never thought to
check.  If I  think about it, probably not as Electron is not backward
compatible in this area neither should Floss be.
You could set the lower limit, just in case and up the major version of
your package accordingly.

If I can do more, let me know.

Ttyl,
John

**Comment by bigtimebuddy** [comment]
The reason I ask is I'm trying to figure out if this is a breaking change or not. I'm okay with merging it, but I don't know how to release. Will try running with Electron 12

**Comment by ztalbot2000** [comment]
I'll give it a try as well.  Will have an update for you by tomorrow noon
EST

Ttyl,
John

**Comment by ztalbot2000** [comment]
Hi,

  I tried to add my floss repository to my old PIXI_UI_IWM repo.
Unfortunately it is so old that it used Electron v8. Updating to v12 gave
me other errors for canvas.
  This is why my PixiV6 branch of my UI repo needed to be upgraded and with
it floss. So unfortunately I cannot determine if it is backward compatible
with my repo.

Now ***@***.***/remote": "^2.0.8" requires electron: "^13.0.0"

  I did try npm run test on floss from your master with my changes to
main.ts, renderer.ts and specifically with "electron": "14.2.9" and adding
***@***.***/remote":"^2.0.8". Your tests pass.

Since so much has changed with Electron, it would probably be safest to
bump the peer dependency minimum and with it the major version of floss as
I cannot verify it independently using my repo. I guess the choice is yours.

Take care,
John

**Comment by ztalbot2000** [comment]
I did a further change (no merge request) to update electron to 21.1.1 and
all seems okay as well.
"floss": "git://
github.com/ztalbot2000/floss#73067338e823dfcadb362ee3e5f6d93639e71a90",

ttyl
John

**Pull request closed without merging**
